---
latitude: 40.75905
longitude: -73.98844
map_zoom: 12
name: Row NYC Test Express Suite
email: steffan@traveltripper.io
phone_number: 001-111-1111
address:
  street1: 700 8th Avenue
  street2: ''
  state: New York
  city: New York
  country: United States
  zip_code: '10036'
_hotel_id: ROW066
_portal_id: required-but-empty
_root_path: https://rt3api-prd.ttaws.com
